export const api = {
  Department: [
    "Home & Kitchen",
    "Kitchen & Dining",
    "Bedding Sheets & Pillowcases",
    "Household Supplies",
    "Computer Accessories & Peripherals",
    "Office & School Supplies",
    "Tools & Home Improvement",
    "Other Office Equipment",
    "Health , Household & Baby Care",
    "Electronics",
    "Industrial & Scientific",
    "Clothing , Shoes & Jewelry",
    "Office Products",
    "Video Games",
    "Arts, Crafts & Sewing",
    "Beauty & Personal Care",
    "Books",
    "Cell Phones & Accessories",
    "Sports & Outdoors",
  ],
  Star: [
    { star: 4, position: "-2px -84px" },
    { star: 3, position: "-293px -180px" },
    { star: 2, position: "-99px -132px" },
    { star: 1, position: "-390px -228px" },
  ],
  Brand: [
    "Amazone Basics",
    "Bedsure",
    "Rayovac",
    "BolBum*S",
    "CGK Unlimited",
    "Linen Home",
    "EcoAqua",
    "Utopia Towels",
  ],
  Color: [
    { type: "black", color: "0px 0px", position: "0px -100px" },
    { type: "gray", color: "-100px 0px", position: "-100px -100px" },
    { type: "white", color: "-200px 0px", position: "-200px -100px" },
    { type: "brown", color: "-300px 0px", position: "-300px -100px" },
    { type: "pink", color: "-400px 0px", position: "-400px -100px" },
  ],

  Product: [
    {
      title: "Best for Bakers",
      name: "Nordic Ware Natural Aluminum Commercial Baker's Half Sheet, 2-Pack, Silver",
      image: "https://m.media-amazon.com/images/I/71PH78qporL._AC_UL320_.jpg",
      star: { number: 5, position: "-166px -36px" },
      numberVote: "100,038",
      dolar: 27,
      cent: 50,
      per: "($13.75/Count)",
      prime: true,
      content:
        "This pack of two aluminum baking sheets is a kitchen must-have.",
    },
    {
      title: "Best for Home Cooks",
      name: 'Lodge Pre-Seasoned Cast Iron Skillet, 10.25", Black',
      image: "https://m.media-amazon.com/images/I/517cJC1ys7L._AC_UL320_.jpg",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "31,913",
      dolar: 17,
      cent: 90,
      per: "$26.68",
      prime: true,
      content:
        "Lodge cookware has long been a favorite among home cooks, and you can shop classic items from the brand like this pre-seasoned cast iron skillet.",
    },
    {
      title: "Best Small Appliance",
      name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker, Slow Cooker, Rice Cooker, Steamer, Sauté, Yogurt Maker, Warmer & Sterilizer, 6 Quart, Stainless Steel/Black",
      image: "https://m.media-amazon.com/images/I/71WtwEvYDOS._AC_UL320_.jpg",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "133,341",
      dolar: 89,
      cent: 11,
      per: null,
      prime: true,
      content:
        "It comes as no surprise that the Instant Pot ended up on our list of favorite home items.",
    },
    {
      title: "Best for Meal Prep",
      name: "Hamilton Beach Food Processor & Vegetable Chopper for Slicing, Shredding, Mincing, and Puree, 10 Cups - Bowl Scraper, Stainless Steel",
      image: "https://m.media-amazon.com/images/I/81y3HTZHzKL._AC_UL320_.jpg",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "27,005",
      dolar: 54,
      cent: 99,
      per: null,
      prime: true,
      content:
        "Another kitchen must-have, this food processor can chop, mix, and puree ingredients for your favorite recipes.",
    },
    {
      title: "Best Closet Space-Saver",
      name: "Amazon Basics Slim, Velvet, Non-Slip Suit Clothes Hangers, Black/Silver - Pack of 30",
      image: "https://m.media-amazon.com/images/I/51hlZZOBpdL._AC_UL320_.jpg",
      star: { number: 5, position: "-166px -36px" },
      numberVote: "128,669",
      dolar: 16,
      cent: 49,
      per: "($0.55/Count)",
      prime: true,
      content:
        "Ideal for small closets, these slim velvet hangers take up less space than wood or plastic options.",
    },
    {
      title: "Best for Laundry",
      name: "Amazon Basics Foldable Laundry Rack for Air Drying Clothing - 41.8 x 29.5 x 14.5, White",
      image: "https://m.media-amazon.com/images/I/61RGvnVS3ZL._AC_UL320_.jpg",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "37,552",
      dolar: 30,
      cent: 99,
      per: "($13.75/Count)",
      prime: true,
      content:
        "Instead of hanging delicates to dry on your shower rod (we’ve all been there), invest in a laundry rack that you can use and store as needed",
    },
    {
      title: "Best for Bedrooms",
      name: "Linenspa, Queen 2 Inch Gel Infused Memory Foam Mattress Topper",
      image: "https://m.media-amazon.com/images/I/81eNPaIPTeL._AC_UL320_.jpg",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "67,914",
      dolar: 59,
      cent: 99,
      per: null,
      prime: true,
      content: "You don’t have to buy a new mattress to upgrade your bed.",
    },
  ],
  ProductApi: [
    {
      title: true,
      name: "Amazon Basics 48 Pack AA High-Performance Alkaline Batteries, 10-Year Shelf Life, Easy to Open Value Pack",
      image: "https://m.media-amazon.com/images/I/71IdKRlm8+L._AC_UL320_.jpg",
      count: "Single Use · 48 Count (Pack of 1)",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "366,575",
      dolar: 14,
      cent: 99,
      per: "($0.31/Count)",
      discount: "$14.24 with Subscribe & Save discount",
      prime: true,
      time: "Get it as soon as Tue, Sep 28",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping on orders over $25 shipped by Amazon",
      color: "pink",
      mutltiColor: null,
      brand: "Amazone Basics",
    },
    {
      title: true,
      name: "Amazon Basics 36 Pack AAA High-Performance Alkaline Batteries, 10-Year Shelf Life, Easy to Open Value Pack",
      image: "https://m.media-amazon.com/images/I/71nDX36Y9UL._AC_UL320_.jpg",
      count: "Single Use · 36 Count (Pack of 1)",
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "352,993",
      dolar: 10,
      cent: 99,
      per: "($0.31/Count)",
      discount: "$10.44 with Subscribe & Save discount",
      prime: true,
      time: "Get it as soon as Tue, Sep 28",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping on orders over $25 shipped by Amazon",
      color: "pink",
      mutltiColor: null,
      brand: "Amazone Basics",
    },
    {
      title: false,
      name: "AmazonBasics Electric Glass and Steel Kettle - 1.7 Liter (Renewed)",
      image: "https://m.media-amazon.com/images/I/81K3EWoTopL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "92",
      dolar: 29,
      cent: 66,
      per: "$32.59",
      discount: null,
      prime: true,
      time: "Get it as soon as Tue, Sep 28",
      remain: "Only 2 left in stock - order soon",
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping by Amazon",
      color: "white",
      mutltiColor: null,
      brand: "Amazone Basics",
    },
    {
      title: true,
      name: "Amazon Basics 8 Pack 9 Volt Performance All-Purpose Alkaline Batteries, 5-Year Shelf Life, Easy to Open Value Pack",
      image: "https://m.media-amazon.com/images/I/711MfFWIoGL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "122,204",
      dolar: 11,
      cent: 99,
      per: "($1.50/Count)",
      discount: "$11.39 with Subscribe & Save discount",
      prime: true,
      time: "Get it as soon as Tue, Sep 28",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping on orders over $25 shipped by Amazon",
      color: "pink",
      mutltiColor: null,
      brand: "Amazone Basics",
    },
    {
      title: false,
      name: "Teraves L Shaped Desk with Shelves Gaming Desk with Large Desktop Corner Desk for Home Office",
      image: "https://m.media-amazon.com/images/I/71pOzrXNVkS._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "72",
      dolar: 259,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it  as soon as Fri, Oct 1 - Fri, Oct 8",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping",
      color: "gray",
      mutltiColor: ["#DFDDDC", "#574534"],
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics Nylon USB-A to Lightning Cable Cord, MFi Certified Charger for Apple iPhone, iPad, Dark Gray, 6-Ft, 2-Pack",
      image: "https://m.media-amazon.com/images/I/61stA5Z9W0L._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "32,669",
      dolar: 21,
      cent: 99,
      per: null,
      discount: null,
      prime: true,
      time: "Get it as soon as Tue, Sep 28",
      remain: null,
      newDolarOffer: "$18.80",
      titleOffer: "(3 used & new offers)",
      content:
        "FREE Shipping on orders over $25 shipped by Amazon More Buying Choices",
      color: "white",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics Coat Locker, 5-Section with Bench",
      image: "https://m.media-amazon.com/images/I/91cprvIUaXL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "158",
      dolar: 262,
      cent: 12,
      per: null,
      discount: "$14.24 with Subscribe & Save discount",
      prime: true,
      time: null,
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping by Amazon In stock soon.",
      color: "pink",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: 'Amazon Basics Lightweight Super Soft Easy Care Microfiber Bed Sheet Set with 14" Deep Pockets - King, Bright White ',
      image: "https://m.media-amazon.com/images/I/61IeZGjFE7L._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "282,407",
      dolar: 23,
      cent: 99,
      per: "($0.31/Count)",
      discount: "$14.24 with Subscribe & Save discount",
      prime: true,
      time: "Get it as soon as Thu, Sep 30",
      remain: null,
      newDolarOffer: "$21.49",
      titleOffer: "(5 used & new offers)",
      content:
        "FREE Shipping on orders over $25 shipped by Amazon More Buying Choices",
      color: "white",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics Tritan 22 Piece (11 Containers and 11 Lids) Locking Food Storage Container - Clear",
      image: "https://m.media-amazon.com/images/I/811RbXeLjNL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "4,859",
      dolar: 34,
      cent: 99,
      per: null,
      discount: null,
      prime: true,
      time: "Get it as soon as Wed, Sep 29",
      remain: null,
      newDolarOffer: "$31.33",
      titleOffer: "(5 used & new offers)",
      content: "FREE Shipping by Amazon More Buying Choices",
      color: "brown",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics Tritan 22 Piece (11 Containers and 11 Lids) Locking Food Storage Container - Clear",
      image: "https://m.media-amazon.com/images/I/81iMHrpqygL._AC_UL320_.jpg",
      count: null,
      star: { number: 4, position: "-84px -8px" },
      numberVote: "55",
      dolar: 238,
      cent: 15,
      per: "($0.31/Count)",
      discount: "Save more with Subscribe & Save",
      prime: true,
      time: "Get it as soon as Wed, Sep 29",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping by Amazon",
      color: "brown",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics 12-Piece Color-Coded Kitchen Knife Set, 6 Knives with 6 Blade Guards, Multi-color",
      image: "https://m.media-amazon.com/images/I/71iB-QmRWEL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "10,352",
      dolar: 15,
      cent: 95,
      per: "($0.31/Count)",
      discount: "Save more with Subscribe & Save",
      prime: true,
      time: "Get it as soon as Thu, Sep 30",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "FREE Shipping on orders over $25 shipped by Amazon",
      color: "black",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: true,
      name: "Amazon Basics Multipurpose Copy Printer Paper - White, 8.5 x 11 Inches, 5 Ream Case (2,500 Sheets)",
      image: "https://m.media-amazon.com/images/I/71ZbDY1fdrS._AC_UL320_.jpg",
      count: null,
      star: { number: 5, position: "-166px -36px" },
      numberVote: "73,329",
      dolar: 24,
      cent: 99,
      per: "($0.31/Count)",
      discount: "$23.74 with Subscribe & Save discount",
      prime: true,
      time: "Get it as soon as Wed, Sep 29",
      remain: null,
      newDolarOffer: "$22.99",
      titleOffer: "(5 userd & new offers)",
      content:
        "FREE Shipping on orders over $25 shipped by Amazon More Buying Choices",
      color: "white",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Gibson Soho Lounge Dinnerware set, Square, Purple",
      image: "https://m.media-amazon.com/images/I/71KHJ9O7YFL._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "27,478",
      dolar: 49,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$44.11",
      titleOffer: "(12 used & new offers)",
      content: "More Buying Choices",
      color: "black",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Home Zone Living 7.6 Gallon Kitchen Trash Can - Pull Out Under Cabinet Trash Bin, Dual Compartment Recycling Combo, 29 Liter",
      image: "https://m.media-amazon.com/images/I/61tRiQF8b0L._AC_UL320_.jpg",
      count: null,
      star: { number: 4.5, position: "-84px -28px" },
      numberVote: "974",
      dolar: 83,
      cent: 33,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$44.11",
      titleOffer: "(8 used & new offers)",
      content: "More Buying Choices",
      color: "black",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "BLUE GINKGO Over the Sink Colander Strainer Basket - Wash Vegetables and Fruits, Drain Cooked Pasta and Dry Dishes - Extendable - New Home Kitchen Essentials (7.9 W x 14.5-19.5 L x 2.75 H) (Pink)",
      image: "https://m.media-amazon.com/images/I/710HekWxw4L._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "4,287",
      dolar: 16,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$12.99",
      titleOffer: "(2 used & new offers)",
      content: "More Buying Choices",
      color: "brown",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Greenco Refrigerator Organizer Bins, Stackable Fridge Organizer, Set of 6, Storage Containers with Durable Handles, Kitchen Organization Freezer, Pantry and Cabinets - BPA Free, Shatter Proof, Clear",
      image: "https://m.media-amazon.com/images/I/81mgOAQmSEL._AC_UL320_.jpg",
      count: null,
      star: { number: 3.5, position: "-181px -56px" },
      numberVote: "5,722",
      dolar: 29,
      cent: 99,
      per: "$39.99",
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$26.99",
      titleOffer: "(9 used & new offers)",
      content: "More Buying Choices",
      color: "black",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Artoid Mode Merry Grinchmas Christmas Table Runner Black, Seasonal Winter Xmas Holiday Kitchen Dining Table Decoration for Indoor Outdoor Home Party Decor 13 x 108 Inch",
      image: "https://m.media-amazon.com/images/I/71YBoFkdiDL._AC_UL320_.jpg",
      count: null,
      star: { number: 3.5, position: "-181px -56px" },
      numberVote: "43",
      dolar: 15,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "More Buying Choices",
      color: "black",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: 'WiseLife Kitchen Mat Cushioned Anti Fatigue Floor Mat,17.3"x28", Thick Non Slip Waterproof Kitchen Rugs and Mats,Heavy Duty Foam Standing Mat for Kitchen,Floor,Home,Office,Desk,Sink,Laundry, Grey',
      image: "https://m.media-amazon.com/images/I/81SedN0uHYL._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "5,949",
      dolar: 12,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "More Buying Choices",
      color: "gray",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Utopia Towels Kitchen Towels, Pack of 12, 15 x 25 Inches, 100% Ring Spun Cotton Super Soft and Absorbent Grey Dish Towels, Tea Towels and Bar Towels",
      image: "https://m.media-amazon.com/images/I/A1iQv-Sx+KS._AC_UL320_.jpg",
      count: null,
      star: { number: 3.5, position: "-181px -56px" },
      numberVote: "34,669",
      dolar: 19,
      cent: 39,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "More Buying Choices",
      color: "brown",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: "Amazon Basics Anti-Fatigue Standing Comfort Mat for Home and Office - 20 x 36-Inch, Dark Brown",
      image: "https://m.media-amazon.com/images/I/81dvb8M-G1L._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "6,646",
      dolar: 29,
      cent: 99,
      per: null,
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$24.10",
      titleOffer: "(6 used & new offers)",
      content: "More Buying Choices",
      color: "brown",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: false,
      name: 'Sweet Home Collection Chair Cushion Crushed Memory Foam Pads Premium Slip Non Skid Microdot Rubber Back Tufted 16" x 16" x 3.25" Thick Seat Cover, 4 Count (Pack of 1), Taupe',
      image: "https://m.media-amazon.com/images/I/81-9QqAtR2L._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "1,127",
      dolar: 49,
      cent: 99,
      per: "($12.25/Count)",
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: "Only 8 left in stock - order soon.",
      newDolarOffer: null,
      titleOffer: null,
      content: "More Buying Choices",
      color: "pink",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: true,
      name: "Corner Shelf, Greenco 5 Tier Floating Shelves for Wall, Easy-to-Assemble Wall Mount Corner Shelves for Bedrooms and Living Rooms, Rustic Walnut Finish",
      image: "https://m.media-amazon.com/images/I/61XhdNvNLdL._AC_UL320_.jpg",
      count: null,
      star: { number: 3.5, position: "-181px -56px" },
      numberVote: "39,981",
      dolar: 19,
      cent: 99,
      per: "$22.99",
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$16.81",
      titleOffer: "(10 used & new offers)",
      content: "More Buying Choices",
      color: "pink",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: true,
      name: "Creative Co-op EC0125 Distressed Wood 2-Tier Tray with Metal Handle, Cream",
      image: "https://m.media-amazon.com/images/I/610B9UP1N2L._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "4,614",
      dolar: 38,
      cent: 99,
      per: "$104.99",
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: null,
      titleOffer: null,
      content: "More Buying Choices",
      color: "pink",
      mutltiColor: null,
      brand: "Bedsure",
    },
    {
      title: true,
      name: "Dash Safe Slice Mandoline Slicer, Julienne + Dicer for Vegetables, Meal Prep & More with 30+ Presets & Thickness Adjuster - Grey",
      image: "https://m.media-amazon.com/images/I/71acmxmPdLL._AC_UL320_.jpg",
      count: null,
      star: { number: 3, position: "-84px -48px" },
      numberVote: "11,810",
      dolar: 29,
      cent: 99,
      per: "$49.99",
      discount: null,
      prime: false,
      time: "Get it as soon as Tue, Jan 4",
      remain: null,
      newDolarOffer: "$26.99",
      titleOffer: "(5 used & new offers)",
      content: "More Buying Choices",
      color: "gray",
      mutltiColor: null,
      brand: "Bedsure",
    },
  ],
};
